apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/DrHoward/ArgoCD-Demo.git
    targetRevision: main
    path: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
